spring:
  application:
    name: eternal-sfedu
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://${DB_URL}:5432/${DB_NAME}"
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
        current_session_context_class: thread
    hibernate:
      ddl-auto: update

server:
  port: 9090
